---
title: "Wisconsin"
author: "Hong Qin"
date: "May 19, 2020"
output:
  html_document: default
  pdf_document: default
---

> ## Disclaimer
> * This analysis is only meant for educational purpose only. 

```{r}
rm(list=ls())
library(tidyverse)
library(readr)
library(dplyr)
library(R0)
```

```{r}
infile ="time_series_covid19_confirmed_US.csv"
tb = read_csv(infile)
head(tb)
tb.ori = tb 
```

# pick Wisconsin
```{r}
tb = tb[ tb$Province_State == 'Wisconsin'  ,   ]
tb.ori = tb 
```


```{r}
colnames = names(tb)
primary = '4/7/20'
start1 = (1:length(tb[1,]))[colnames == "1/22/20"]
start2 = (1:length(tb[1,]))[colnames == "4/21/20"]
```

#my plan: 
split the input file into two: before and after, then process the two different files twice, estimate R0, then do t.test


```{r}
(1:length(names(tb))) [names(tb)=='4/7/20']
tb.bf = tb[, 12:87 ]

(1:length(names(tb))) [names(tb)=='4/21/20']
tb.af= tb[,102:122  ]
```

#pick a row from tibble
```{r}
tb.bf = as.data.frame(tb.bf)
tb.bf= tb.bf[ tb.bf$`4/6/20` > 20, ] #16 rows
```

```{r}
tb = tb.bf
total.timepoints = 76

debug = 0

#i= 68
for( i in 1:16){
 x = as.vector(t(tb[i,1:76])) 
 for (j in 2:length(x)){
   x[j] = x[j] - x[j-1]
 }
 x[x<0] = 0
 
 #str(x)
 if ( max(x) > 20 ) {
   mGT= generation.time("gamma", c(3, 1.5))
   R0EG = estimate.R(x, GT=mGT,  methods=c('EG'), pop.size = 100000, nsim=10 )
   tb$R0EG[i] = as.numeric(unlist(R0EG$estimates$EG$R))
  } else {
    tb$R0EG[i]  = NA
  }
}

hist(tb$R0EG)
tb.bf.R0EG = tb$R0EG
```



```{r}
(1:length(names(tb))) [names(tb.ori)=='4/21/20']
tb.af= tb.ori[,102:122  ]
tb.af = as.data.frame(tb.af)
tb.af= tb.af[ tb.af$`5/11/20` > 30, ] # 23 rows

total.timepoints = 21

debug = 0
tb = tb.af

#i= 20
for( i in 1:23){
 x = as.vector(t(tb[i,1:21])) 
 for (j in 2:length(x)){
   x[j] = x[j] - x[j-1]
 }
 x[x<0] = 0
 
 #str(x)
 if ( max(x, na.rm=T) > 20 ) {
   mGT= generation.time("gamma", c(3, 1.5))
   R0EG = estimate.R(x, GT=mGT,  methods=c('EG'), pop.size = 100000, nsim=10 )
   tb$R0EG[i] = as.numeric(unlist(R0EG$estimates$EG$R))
  } else {
    tb$R0EG[i]  = NA
  }
}

hist(tb$R0EG)
tb.af.R0EG = tb$R0EG
```


```{r}
t.test( tb.bf.R0EG, tb.af.R0EG)
```


