---
title: "yeast PIN degree Z-score"
author: "H Qin"
date: "11/1a/2018"
output:
  html_document: default
  pdf_document: default
---

```{r read.csv}
rm(list=ls())
start = Sys.time()
debug = 5
library(igraph)
pairs= read.csv("Data/yeast.pin.csv", colClasses = c("character", "character"))
```
```{r}
allCombinationsOfTwoVectors = function (els1, els2 ) {
  tagbuffer = c();
  for (e1 in els1) {
    for (e2 in els2) {
         tmp = sort(c(e1, e2));
         current_tag = paste(tmp[1], tmp[2], sep="_")
         tagbuffer = c(tagbuffer, current_tag)
    }
  }
  return( tagbuffer)
}
```

```{r degree}
g = graph.data.frame(pairs[, 1:2], directed=F)
g.degree = degree(g)
g.degree [g.degree == max(g.degree)] #TN and MO have 8 bordering states
```

```{r degree2quantile}
#h = hist(log2(g.degree), br = 10)
myq = quantile( g.degree, prob = seq(0, 1, by=0.05))
d.myq = data.frame(myq)
d.myq$Q = rownames(d.myq)
names(d.myq) = c("k", "Q")

degree2Q = function( k ){
  sub = d.myq[ d.myq$k <= k, ]
  return (  sub$Q[ sub$k == max(sub$k)] )
}
degree2Q(1)
degree2Q(2)
degree2Q(1E3)
degree2Q(1E4)

g.q = unlist(lapply( g.degree, degree2Q))
g.q[1:10]
```

# F.obs 

```{r F.obs}
pairs$cat1 = as.character( g.q[pairs$geneA] )
pairs$cat2 = as.character( g.q[pairs$geneB] )
pairs[ pairs$geneA == "YAL002W", ] 
g.degree["YAL002W"] #visual check passed
g.q["YAL002W"] #visual check passed

tags = t(apply(pairs[,c("cat1", "cat2")], 1, sort))
pairs$tag = paste( tags[,1], tags[,2], sep='_')
F.obs = data.frame( table(pairs$tag))
names(F.obs) = c("tag", "freq")
F.obs [1:10,]
```

#load MS02 null networks
```{r F.ms02}
ms02files = list.files(path='yeastMS02')
if (debug ) {ms02files = ms02files[1: 5] }
F.ms02 = data.frame(matrix(data=NA, nrow=1, ncol=3)) #null distributions
names(F.ms02) = c('tag', 'freq', 'file')

# file = "ms02.1.csv" #debug
for (file in ms02files ){
  if ( debug > 0 ) { print(file) }
  ms02_pairs= read.csv(paste("yeastMS02/", file, sep=''),
                       colClasses = c("character", "character"))
  ms02_pairs = ms02_pairs[,1:2]
  
  ms02_pairs$cat1 = as.character( g.q[ms02_pairs$id1] )
  ms02_pairs$cat2 = as.character( g.q[ms02_pairs$id2] )
  ms02_pairs[ ms02_pairs$id1 == "YAL002W", ] 
  g.degree["YAL002W"] #visual check passed
  g.q["YAL002W"] #visual check passed

  tags2 = t(apply(ms02_pairs[,c("cat1", "cat2")], 1, sort))
  ms02_pairs$tag = paste( tags2[,1], tags2[,2], sep='_')
  F.ms02current = data.frame( table(ms02_pairs$tag))
  F.ms02current$file = file
  names(F.ms02current) = c('tag', 'freq', 'file')
  F.ms02 =  data.frame( rbind(F.ms02, data.frame(F.ms02current)) )
}
F.ms02 = F.ms02[ !is.na(F.ms02$tag), ]
summary(F.ms02)
```

# Initialize the Z-score matrix
```{r}
all_tags = unique( allCombinationsOfTwoVectors(d.myq$Q, d.myq$Q) )
Zs = data.frame(all_tags)
names(Zs) = c('tag')
Zs$freq = ifelse( all_tags %in% Zs$tag, F.obs$freq[ match( Zs$tag , F.obs$tag) ], 0)
Zs$freq[is.na(Zs$freq)] = 0; 
summary(Zs)
```

# calculate Z-score. This take a few minutes. Need be modified by multicore
```{r Zs}
for (i in 1 : length(Zs$tag)) {
#i = 2
  sub = F.ms02[ F.ms02$tag == Zs$tag[i], ]
  if ( length(sub[,1])> 0) {
    Zs$Z[i] = ( Zs$freq[i] - mean(sub$freq) ) / max(sd(sub$freq), 0.5)
    if(debug>1 ){
       print( paste( Zs$tag[i],"lenthg(sub[,1]):",length(sub[,1]), "mean:", mean(sub$freq), "sd:", sd(sub$freq) ))  
       sub
    } 
  } else {
    #Zs$Z[i] = ( Zs$freq[i] - 0 ) / 1E-10  #never observed in ms02 nulls?? what to do??
    Zs$Z[i] = 999  #never observed in ms02 nulls?? what to do??
    if(debug>0 ){
       print( paste( Zs$tag[i],"lenthg(sub[,1]):",length(sub[,1]), "mean:", mean(sub$freq), "sd:", sd(sub$freq) ))  
    } 
  }
}
summary(Zs$Z)
```


# generate Z matrix
```{r Zmat}
#unique categories
cats =  as.character( d.myq$Q ) # do not sort this
Zmat = matrix(NA, ncol=length(cats), nrow=length(cats))
colnames(Zmat) = cats; 
rownames(Zmat) = rev(cats); 
for (i in 1:length(cats)){#row
  for (  j in 1:length(cats)) { #column
    tmp = sort(c(cats[i], rev(cats)[j]))
    mytag = paste(tmp[1], tmp[2], sep="_")
    if( mytag %in% Zs$tag) {
       Zmat[i,j] = Zs$Z[ Zs$tag == mytag ]
    } else {
       Zmat[i,j] = NA
    }
    if (debug >1 ) {
      print (paste(mytag, Zmat[i,j] ) )
    }
  }
}
Zmat
```

#heatmap

```{r}
for( i in 1:length(Zmat[1,])) {
 for( j in 1:length(Zmat[,1])){
   Zmat[i,j] =  ifelse( Zmat[i,j] > 10  , 10, Zmat[i,j] )
   Zmat[i,j] =  ifelse( Zmat[i,j] < -10, -10, Zmat[i,j] )
 }
}

```

```{r heatmap.2}
library(gplots)
#colors = c(seq(min(Zmat),-10.1,length=100),seq(-9.9,9.9,length=100),seq(10.1,max(Zmat),length=100))
my_palette <- colorRampPalette(c("blue2", "white", "red2"))(n = 299)

heatmap.2( as.matrix(Zmat), col=my_palette, scale="none",
          # margins = c(5,4), key.title = NA, 
           ,key.xlab="Z-score", key.ylab=NA,
          dendrogram='none', Rowv=FALSE, Colv=FALSE,trace='none'
          )

```


```{r}
colors = c( seq(min(Zmat, na.rm =T), -10.1, length=100),
            seq(-9.9,9.9,length=100),seq(10.1,max(Zmat,na.rm=T),length=100) )
my_palette <- colorRampPalette(c("blue2", "white", "red2"))(n = 299)


heatmap.2(as.matrix(Zmat), col=my_palette, breaks=colors,
          trace='none', offsetRow = 0, offsetCol = 0,
          #ylab="Biological Process Terms", xlab="Biological Process Terms",
          #margins = c(2,2), key.title = "Color Bar", key.xlab="Z-score", key.ylab=NA,
          #labCol = NA, labRow = NA,
          scale="none", dendrogram = "none", Rowv=FALSE, Colv=FALSE,
          #symbreaks=T, symm=F, symkey = F
          )

```


```{r}
end = Sys.time()
runtime = end - start
print(runtime)
```

