---
title: "test foreach, not working"
author: "H Qin"
date: "11/1a/2018"
output:
  html_document: default
  pdf_document: default
---


```{r}
rm(list=ls())
start = Sys.time()
debug = 10
library(igraph)
pairs= read.csv("Data/yeast.pin.csv", colClasses = c("character", "character"))
if ( debug > 9) { pairs = pairs[c(1:100, 900:1000), ]}
names(pairs) = c("name1", "name2")
```

# Load yeast GO terms
```{r}
YeastBP = read.csv("Data/yeast.bp.gene.term.csv", colClasses = c("character", "character", "character", "character", "character"))
cats = YeastBP;  #cats is a general name
names(cats) = c("id", "gene", "sgd","type", "GO")
```

```{r}
if( debug > 9 ){ #pick large GO terms
  tmp = table( cats$GO)
  largeGOterms =as.character( names(tmp[ tmp >= mean(tmp)]) )
  cats$large_flag = ifelse( cats$GO %in% largeGOterms, 1, 0 )
  table(cats$large_flag)
  cats = cats[ cats$large_flag == 1, ]
}
```


```{r}
allCombinationsOfTwoVectors = function (els1, els2 ) {
  tagbuffer = c();
  for (e1 in els1) {
    for (e2 in els2) {
         tmp = sort(c(e1, e2));
         current_tag = paste(tmp[1], tmp[2], sep="_")
         tagbuffer = c(tagbuffer, current_tag)
    }
  }
  return( tagbuffer)
}
allCombinationsOfTwoVectors(  largeGOterms,  largeGOterms )[ c(1,3,15)] 
```

```{r}
#library(foreach)
#library(doMC)
#library(iterators)
#registerDoMC(2)

#Z.df = data.frame(allCombinationsOfTwoVectors(  largeGOterms,  largeGOterms ))
#names(Z.df) = c("tag")
#Z.df$count = 0

tagbuffer = c()
for(i in 1:nrow(pairs) ) {
  sub1 = cats[ cats$id == pairs$name1[i], ]
  sub2 = cats[ cats$id == pairs$name2[i], ]
 
  localtagbuffer = allCombinationsOfTwoVectors ( sub1$GO, sub2$GO)  #all combinations
  tagbuffer = c(tagbuffer, localtagbuffer )
 
}
F.obs = table(tagbuffer)
```
