
---
title: "Basic R Coding"
author: "H Qin"
date: "5/18/2021"
output:
  html_document: 
    toc: true
    toc_float: true 
---


# loops

## for loops
```{r}
rm(list=ls())
 for ( i in c("red", "blue", "orange")) print( i );
```


```{r}
 for ( i in c(0.5, 1, -2, 5) ) print(i);
```



```{r}
 for ( i in c(0.5, 1, -2, 5) ) {
   x = i * i
   print( sqrt(x))
 }
```

```{r}
 for ( i in c("red", "blue", "orange")) print( i );

```


## while loops 

```{r}
i=2;
 while( i<=10 ) { 
  print(i); 
  i = i + 2; 
 }
```


# conditionals

```{r}
x = 1;
if ((x<1) & (x>0)) { 
   print("X is between 0 and 1 ");
} else {
   print("X is not between 0 and 1");
}
```


```{r}
x =0.5;
if ( ( ! x>1) & ( ! x<0 ) ) {
   print("x is between 0 and 1");
}

if ( x == 0.5 ) {
   print("50%");
}

```


```{r}
x= -1;
if ( ! x<0 ) {
  print("non-negative");
} else {
  print("negative");
}

x = c(-1, 3)
x = c( 1, NA, 3, 4, 5, 2)
y = ifelse( is.na(x), median(x, na.rm = T), x ); 
# assign abosulte value of x to y
print(y)
```

# function and scope of variables

```{r}
#### a function
x = c( 1,2,3,4, 7, 9); #this is a global variable
#x = c(5, 4, 3, 6, 10, 12)

y = "I am global"
```


```{r}
take_even = function( x ) {
  y = c(); # a locale copy inside of loop
  for( i in 1:length(x)) {
    if ( (x[i] %% 2 )== 0 ) { # x mod 2
        y = c(y, x[i] );  # add a new x[i] to y
    }
  }
  print ("inside y");
  print(y)
  print("end of inside")
  y; #the last line, return y to the main program
}

take_even(x); # c(2,4)

print(paste("outside y=", y))

#y =  take_even(x); # c(2,4)

z = take_even(x); # c(2,4);
w = take_even(1:10); #c (2,4,6,8,10)
u = -5:10;
v = take_even(u); # -4 -2  0  2  4  6  8 10
take_even(c(5,4,10,11, 100, -3, 9, 0, 3333, 5524234234))

```


```{r}
#### a function calls another function
even_total = function( x ) {
  x = take_even(x);
  sum(x)
 }

x = c( 1,2,3,4, 0, -2, -4 );
u = even_total( x );
print(u)

# x will be changed if the following line is run.
x = take_even(x)
 
```

 
```{r}
 #### scope of variable 
 x = c( 1,2,3,4); #this is a global variable
 y = c(-1, -2, -3, -4)# this is also a global one
 y.outside = y; 
 take_uphalf = function( x ) {
   y = c(); # a local copy inside of loop
   xbar = mean(x); 
   for( i in 1:length(x)) {
     if ( x[i] > xbar ) { 
       y = c(y, x[i] );
     }
   }
   y.inside = y; 
   print( paste("y.inside=", y.inside) ); 
   y; #the last line, return y to the main program
 }
 
 w = take_uphalf(x);
 mean(x)
 
print( paste("y.outside=", y.outside))
```
 
 
# packages

```{r}
#install packages
 require("ape");
 require("seqinr");

 #load packages
 library(ape);
 library(seqinr);

 #what's in the package?
 help(package=ape);
 help(package=seqinr);
  #you should also read the manual of the packages

```
# save working space
 
```{r}

#### save and load images
 save.image("Test0518.RData");
 
 # delete everyting 
 rm(list=ls());
 
 ls(); #nothing

 load("Test0518.RData");
 ls(); #everthing is back


```
 
 