---
title: "Z-score"
author: "H Qin"
date: "10/26/2018"
output:
  html_document: default
  pdf_document: default
---

```{r}
rm(list=ls())
debug = 1
library(igraph)
pairs= read.csv("seats.csv", colClasses = c("character", "character"))
nodes = read.csv("students.csv", colClasses = c("character", "character"))
```

# Order state, 
```{r}
newpairs = data.frame( t(apply(pairs, 1, sort)) ); #oder id1 and id2
cbind( newpairs, pairs)
```


# convert long names to 2 letter
```{r}
pairs = newpairs
names(pairs) = c("name1", "name2")
pairs$cat1 = nodes$Gender[match( pairs$name1, nodes$Names)]
pairs$cat2 = nodes$Gender[match( pairs$name2, nodes$Names )]

```

```{r}
tags = t(apply(pairs[,c("cat1", "cat2")], 1, sort))
pairs$tag = paste( tags[,1], tags[,2], sep='_')
F.obs = data.frame( table(pairs$tag))
names(F.obs) = c("tag", "freq")
F.obs
```

#load MS02 null networks
```{r}
ms02files = list.files(path='MS02')
F.ms02 = data.frame(matrix(data=NA, nrow=1, ncol=3)) #null distributions
names(F.ms02) = c('tag', 'freq', 'file')

# file = "_ms02_seats.1.csv" #debug

for (file in ms02files ){
  if ( debug > 0 ) { print(file) }
  ms02_pairs= read.csv(paste("MS02/", file, sep=''))
  ms02_pairs = ms02_pairs[,1:2]
  ms02_pairs$cat1 = nodes$Gender[match( ms02_pairs$id1, nodes$Names)]
  ms02_pairs$cat2 = nodes$Gender[match( ms02_pairs$id2, nodes$Names)]
  
  tags2 = t(apply(ms02_pairs[,c("cat1", "cat2")], 1, sort))
  ms02_pairs$tag = paste( tags2[,1], tags2[,2], sep='_')
  F.ms02current = data.frame( table(ms02_pairs$tag))
  F.ms02current$file = file
  names(F.ms02current) = c('tag', 'freq', 'file')
  F.ms02 =  data.frame( rbind(F.ms02, data.frame(F.ms02current)) )
}
F.ms02 = F.ms02[ !is.na(F.ms02$tag), ]
```

# Initialize the Z-score matrix
```{r}
unique_tags = unique( c(as.character(F.obs$tag), as.character(F.ms02$tag)))
Zs = data.frame(unique_tags)
names(Zs) = c('tag')
Zs$freq = F.obs$freq[ match( Zs$tag , F.obs$tag) ]
Zs$freq[is.na(Zs$freq)] = 0; 
Zs
```

# calculate Z-score
```{r}
for (i in 1 : length(Zs$tag)) {
#i = 2
  sub = F.ms02[ F.ms02$tag == Zs$tag[i], ]
  if(debug>0 ){
     print( paste( Zs$tag[i], "mean:", mean(sub$freq), "sd:", sd(sub$freq) ))  
  } 
  Zs$Z[i] = ( Zs$freq[i] - mean(sub$freq) ) / max(sd(sub$freq), 0.5)
}
```

# split the tags
```{r}
#tmp = as.vector(unlist(strsplit(as.character(Zs$tag), split="_")))
#tmp2 = data.frame( matrix( tmp, nrow=10, ncol=2, byrow = T) )
#names(tmp2) = c('c1', 'c2')
#Zs = cbind( Zs, tmp2)
```

# generate Z matrix
```{r}
#unique categories
cats = sort( unique( nodes$Gender ))
Zmat = matrix(NA, ncol=length(cats), nrow=length(cats))
names(Zmat) = cats; 
colnames(Zmat) = cats; 
for (i in 1:length(cats)){#row
  for (  j in 1:length(cats)) { #column
    tmp = sort(c(cats[i], cats[j]))
    mytag = paste(tmp[1], tmp[2], sep="_")
    Zmat[i,j] = Zs$Z[ Zs$tag == mytag ]
    if (debug ) {
      print (paste(mytag, Zmat[i,j] ) )
    }
  }
}
Zmat
```

#heatmap
```{r}
library(Heatplus)
heatmap_2( Zmat,scale="none", legend=4, do.dendro=c(T,F), col=RGBColVec(64));
```

```{r}
heatmap_2(Zmat, legend=4, col=RGBColVec(64))
```

