---
title: "Z-score, multi-labeled nodes"
author: "H Qin"
date: "10/29/2018"
output:
  html_document: default
  pdf_document: default
---

```{r}
rm(list=ls())
debug = 1
library(igraph)
pairs= read.csv("seats.csv", colClasses = c("character", "character"))
nodes = read.csv("students2.csv", colClasses = c("character", "character", "character"))
names(pairs) = c("name1", "name2")
```

# hobbies added to pairs. 
Depending on the how nodes are labeled, this step can be done during the couting process. 

```{r}
pairs$hobbies1 = nodes$hobbies[match( pairs$name1, nodes$Names)]
pairs$hobbies2 = nodes$hobbies[match( pairs$name2, nodes$Names )]
```

# function to find out all combinations of two vectors
```{r}
allCombinationsOfTwoVectors = function (els1, els2 ) {
  tagbuffer = c();
  for (e1 in els1) {
    for (e2 in els2) {
         tmp = sort(c(e1, e2));
         current_tag = paste(tmp[1], tmp[2], sep="_")
         tagbuffer = c(tagbuffer, current_tag)
    }
  }
  return( tagbuffer)
}
```

```{r}
allCombinationsOfTwoVectors( c("one", "two"), c("red", "blue", "orange"))
```

```{r}
x = allCombinationsOfTwoVectors( c("1", "2", "red"), c("red", "blue", "orange", "2"))
length(x)
table(x)
```

```{r}
pairsBuffer = data.frame(matrix(NA, nrow = 1, ncol=3))
names(pairsBuffer) = c("name1", "name2", "tag")
for ( i in 1:length(pairs[,1])){
  els1 = sort( unlist( strsplit(  pairs$hobbies1[i], split=",") ))
  els2 = sort( unlist( strsplit(  pairs$hobbies2[i], split=",") ))
  tagbuffer = allCombinationsOfTwoVectors ( els1, els2)  #all combinations
  
  # generate a dataframe buffer with ids
  currentBuffer = data.frame( cbind(rep(pairs$name1[i], length(tagbuffer)), 
                        rep(pairs$name2[i], length(tagbuffer)), 
                        tagbuffer                        ))
  names(currentBuffer) = c("name1", "name2", "tag")
  
  pairsBuffer = rbind( pairsBuffer, currentBuffer) #combine with dataframe buffer
}

F.obs = data.frame( table(pairsBuffer$tag))
names(F.obs) = c("tag", "freq")
F.obs
```

#load MS02 null networks
```{r}
ms02files = list.files(path='MS02')
F.ms02 = data.frame(matrix(data=NA, nrow=1, ncol=3))
names(F.ms02) = c('tag', 'freq', 'file')

# file = "_ms02_seats.1.csv" #debug
for (file in ms02files ){
  if ( debug > 0 ) { print(file) }
  ms02_pairs= read.csv(paste("MS02/", file, sep=''), colClasses = c("character", "character"))
  ms02_pairs = ms02_pairs[,1:2]
  names( ms02_pairs) = c("name1", "name2")
  ms02_pairs$hobbies1 = nodes$hobbies[match( ms02_pairs$name1, nodes$Names)]
  ms02_pairs$hobbies2 = nodes$hobbies[match( ms02_pairs$name2, nodes$Names )]

  pairsBuffer = data.frame(matrix(NA, nrow = 1, ncol=3))
  names(pairsBuffer) = c("name1", "name2", "tag")
  for ( i in 1:length(ms02_pairs[,1])){
    els1 = sort( unlist( strsplit( ms02_pairs$hobbies1[i], split=",") ))
    els2 = sort( unlist( strsplit( ms02_pairs$hobbies2[i], split=",") ))
    tagbuffer = allCombinationsOfTwoVectors ( els1, els2)  #all combinations
  
    # generate a dataframe buffer with ids
    currentBuffer = data.frame( cbind(rep(ms02_pairs$name1[i], length(tagbuffer)), 
                        rep(ms02_pairs$name2[i], length(tagbuffer)), 
                        tagbuffer                        ))
    names(currentBuffer) = c("name1", "name2", "tag")
  
    pairsBuffer = rbind( pairsBuffer, currentBuffer) #combine with dataframe buffer

  }#ms02_pair loop
  
  F.ms02current = data.frame( table(pairsBuffer$tag))
  F.ms02current$file = file
  names(F.ms02current) = c('tag', 'freq', 'file')
  F.ms02 =  data.frame( rbind(F.ms02, data.frame(F.ms02current)) )

}#file loop

F.ms02 = F.ms02[ !is.na(F.ms02$tag), ]
```

# Initialize the Z-score matrix
```{r}
unique_tags = unique( c(as.character(F.obs$tag), as.character(F.ms02$tag)))
Zs = data.frame(unique_tags)
names(Zs) = c('tag')
Zs$tag = as.character(Zs$tag)
Zs$freq = F.obs$freq[ match( Zs$tag , F.obs$tag) ]
Zs$freq[is.na(Zs$freq)] = 0; 
Zs
```

# calculate Z-score
```{r}
for (i in 1 : length(Zs$tag)) {
#i = 2
  sub = F.ms02[ F.ms02$tag == Zs$tag[i], ]
  if(debug>0 ){
     print( paste( Zs$tag[i], "mean:", mean(sub$freq), "sd:", sd(sub$freq) ))  
  } 
  Zs$Z[i] = ( Zs$freq[i] - mean(sub$freq) ) / max(sd(sub$freq), 0.5) 
}
```

# split the tags
```{r}
tmp = as.vector(unlist(strsplit(as.character(Zs$tag), split="_")))
tmp2 = data.frame( matrix( tmp, nrow=length(Zs[,1]), ncol=2, byrow = T) ) #fix error, 20181031
names(tmp2) = c('c1', 'c2')
Zs = cbind( Zs, tmp2)
```

# generate Z matrix
```{r}
#unique categories
cats = sort( unique( c(as.character(Zs$c1), as.character(Zs$c2)) ))
Zmat = data.frame( matrix(NA, ncol=length(cats), nrow=length(cats)) )
names(Zmat) = cats; 
rownames(Zmat) = cats; 
for (i in 1:length(cats)){#row
  for (  j in 1:length(cats)) { #column
    tmp = sort(c(cats[i], cats[j]))
    mytag = paste(tmp[1], tmp[2], sep="_")
    if ( mytag %in% Zs$tag ) {
      Zmat[i,j] = Zs$Z[ Zs$tag == mytag ]
    } else { #tag was never found? !
      Zmat[i,j] = NA
    }
    if (debug ) {
      print (paste(mytag, Zmat[i,j] ) )
    }
  }
}
Zmat
```

# heatmap

```{r}
library(gplots)
#colors = c(seq(min(Zmat),-10.1,length=100),seq(-9.9,9.9,length=100),seq(10.1,max(Zmat),length=100))
my_palette <- colorRampPalette(c("blue2", "white", "red2"))(n = 299)

heatmap.2( as.matrix(Zmat), col=my_palette, scale="none", trace='none',
           dendrogram = "none", Rowv = FALSE, Colv = FALSE
          # margins = c(5,4), key.title = NA, 
           ,key.xlab="Z-score", key.ylab=NA,
          )

```


```{r}
#heatmap.2(as.matrix(Zmat), dendrogram = "none", Rowv = FALSE, Colv = FALSE)
```

