---
title: "Input and output in R"
author: "H Qin"
date: "5/18/2021"
output:
  html_document: 
    toc: true
    toc_float: true 
---

# Read a data set of yeast growth curves

```{r}
rm(list=ls()) #clearn my workspace
library(tidyverse)
tb = read.csv("Carlson_Yeast.csv");
```

 # a simple plot
```{r}
plot( tb$Amount ~ tb$Hours );
```

 # a better plot

```{r}
 plot( Amount ~ Hours, data=tb );
```


```{r}
 plot( Amount ~ Hours, data=tb, type="b",
    main="Carlson growth curve" );
```

# Multiple data sets plotted in the same figure 

```{r}
##### the second data set, multiple plots
 tb2 = read.csv( "Carlson2.csv" );

 ##first try, not pretty
 plot( tb2$Amount ~ tb2$Hours, ylab="Amount",xlab="Hours",type="l", 
    main="growth comparison");
 lines( tb2$Amount2 ~ tb2$Hours );

```

```{r}
 ##now, let's add colors
 plot( tb2$Amount ~ tb2$Hours, ylab="Amount",xlab="Hours",type="l",  lty=2, ylim=c(-100, 1000),
    main="growth comparison", col="blue");
 lines( tb2$Amount2 ~ tb2$Hours, col="red", lwd=1 );

 ##add legends
 #legend(2,500,c("Amount","Amount2"), col=c("blue","red"), lwd=c(1,1) )
#legend(12,250        ,c("wt","mutant"), col=c("blue","red"), lwd=c(1,1), lty=c(2,1) )

#legend("bottomright", c("Amount, second amount"))
#legend('bottomright',500,c("wt","mutant"), col=c("blue","red"), lwd=c(1,1))
legend(("bottomright"), c("WT", "MUT"), col=c("Blue","Red"),lwd=c(1,1), lty=c(2,1))

```

```{r}
library(reshape2)
selected_columns = c('Amount', "Amount2")
df_melt <- melt( tb2, measure.vars=selected_columns )
plot <- ggplot(df_melt, aes(x=Hours, y=value, color=variable)) + geom_point()
plot + ggtitle( "ggplot")
```

```{r}
x = 1:127
y = 1:127
plot( y ~x, pch=x)
```

```{r}
##### plot sunflower seed data
 sunflower = read.csv("SunflowerSeedData.csv");

 plot( sunflower$Stripes ~ sunflower$Seeds, ylab="Stripes"
       , xlab="Seeds", main="sunflower data", type="b"
       , col="red"
       )
```

```{r}
ggplot( sunflower, aes(x=Stripes, y=Seeds)) + geom_area()
```

# Output to csv file 

```{r}
 x= seq(1:30)
 y= x^2;
 write.csv(x, "x.csv", row.names=F)
 write.csv(y, "y.csv", row.names=F)
 output = cbind(x, y)
 write.csv(output, "xy-20210518.csv", row.names=F)
 write.table(output, "xy-202120518.tab", sep="\t", row.names=F)
 
```

```{r}
library(tidyverse)

ggplot( as.data.frame(output), aes(x=x, y=y)) + geom_point()
```

