---
title: "Simple statistics, 2020 Election Reults"
author: "H Qin"
date: "5/18/2021"
output:
  html_document: 
    toc: true
    toc_float: true
---

# Read a data set

```{r}
rm(list=ls()) #clearn my workspace
library(tidyverse)
Election20df = read_csv("https://raw.githubusercontent.com/tonmcg/US_County_Level_Election_Results_08-20/master/2020_US_County_Level_Presidential_Results.csv")
head(Election20df)
```

#Question: What is the total number of votes? 

```{r}
Election20df %>% select ( total_votes ) %>% sum()

sum( Election20df$total_votes )
```

# Question: What are the total number votes for GOP or DEM? 

```{r}
Election20df %>% select ( votes_gop ) %>% sum()
Election20df %>% select ( votes_dem ) %>% sum()

```

# Look at California
```{r}
mystate = "California"
Californiadf <- 
  Election20df %>% filter( state_name == mystate) %>%  arrange( per_point_diff)

names( Californiadf )[8] = "percentage_for_GOP"

ggplot(Californiadf, aes(percentage_for_GOP)) +  geom_histogram()
#summary(Californiadf$per_gop)
```

# Results by States? 

```{r}

Statedf <- Election20df %>% select( state_name, votes_gop, votes_dem,  total_votes ) %>% group_by( state_name ) %>% summarise_if( is.numeric, sum)

Statedf$percentage_for_GOP = Statedf$votes_gop / Statedf$total_votes

ggplot(Statedf, aes(percentage_for_GOP)) +  geom_histogram()
```

# Question: Find out which state has the nearly 100% DEM voting percentage? 

There are many ways to do this. 

```{r}
Statedf %>% filter( percentage_for_GOP < 0.1 )
```

